name: Release Workflow

on:
  push:
    branches:
      - release
  pull_request:
    paths:
      - 'develop/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Run your release script or commands
      run: npm ci
    - name: Bumb version
      run: | 
        git add .
        git commit -m "Bump version for release"
        git push origin develop
      # if: github.event_name == 'pull_request' && github.event.action == 'merged' && contains(github.event.pull_request.labels.*.name, 'merge-to-release')

# Add any additional steps or jobs as needed
